language: python
sudo: required
services:
  - docker
python:
  - 3.6
install:
  - virtualenv -p python3.6 venv
  - ./venv/bin/pip install --upgrade black==18.9b0
  - git clone https://github.com/codalab/codalab-worksheets ../codalab-worksheets
script:
  - cd ./docker/service && ./build-and-start.sh && cd ..
  - ./venv/bin/black . --check
