language: python
sudo: required
services:
  - docker
python:
  - 3.6
install:
  - pip install --upgrade black==18.9b0
script:
  - cd ./docker/service && ./build-and-start.sh --test
  - black . --check
