version: '3'

volumes:
  webserver-static:

services:
  mysql:
    image: mysql:5.5.53
    environment:
      - MYSQL_ROOT_PASSWORD=ROOTPWD
    volumes:
      - ./config/conf.d:/etc/mysql/conf.d

  db-initializer:
    image: codalab/bundleserver:0.2.38
    entrypoint: ['/data/bin/initialize-db.sh']
    depends_on:
      - mysql
    environment:
      - CODALAB_HOME=/home/.codalab
      - CODALAB_USERNAME=codalab
      - CODALAB_PASSWORD=TESTPASSWORD
    volumes:
      - ./initialize-db.sh:/data/bin/initialize-db.sh
      - ./.codalab:/home/.codalab

  rest-server:
    image: codalab/bundleserver:0.2.38
    command: server
    ports:
      - 2900:2900
    environment:
      - CODALAB_HOME=/home/.codalab
      - CODALAB_USERNAME=codalab
      - CODALAB_PASSWORD=TESTPASSWORD
    volumes:
      - ./.codalab:/home/.codalab
    depends_on:
      - db-initializer

  bundle-manager:
    image: codalab/bundleserver:0.2.38
    # sleep 30 seconds to give db-initializer time to initialize the db
    # TODO (bkgoksel): use something better than sleep (still works but logs error messages if sleep time isn't enough)
    entrypoint: bash -c "sleep 30 && /opt/codalab-cli/codalab/bin/cl bundle-manager"
    environment:
      - CODALAB_HOME=/home/.codalab
      - CODALAB_USERNAME=codalab
      - CODALAB_PASSWORD=TESTPASSWORD
    volumes:
      - ./.codalab:/home/.codalab
    depends_on:
      - db-initializer

  web-server:
    image: codalab/webserver:0.2.38
    environment:
      - DJANGO_CONFIGURATION=prod
      - DJANGO_SECRET_KEY=SECRET_KEY
      - DJANGO_ALLOWED_HOSTS=localhost:127.0.0.1
    ports:
      - 2700:2700
    volumes:
      - webserver-static:/opt/codalab-worksheets/codalab/apps/web/static

  nginx:
    image: nginx:1.12.0
    command: /data/bin/wait-for-it.sh rest-server:2900 -- nginx
    ports:
      - 80:80
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
      - webserver-static:www/data
      - ./wait-for-it.sh:/data/bin/wait-for-it.sh
