version: '3'

volumes:
  webserver-static:

services:
  mysql:
    image: mysql:5.5.53
    environment:
      - MYSQL_ROOT_PASSWORD=ROOTPWD
    volumes:
      - ./files/config/conf.d:/etc/mysql/conf.d

  db-initializer:
    image: codalab/bundleserver:local-dev
    entrypoint: ['/data/bin/initialize-db.sh']
    depends_on:
      - mysql
    environment:
      - CODALAB_HOME=/home/codalab
      - CODALAB_USERNAME=codalab
      - CODALAB_PASSWORD=TESTPASSWORD
    volumes:
      - ./files/initialize-db.sh:/data/bin/initialize-db.sh
      - ./files/config/config.json:/home/codalab/config.json

  rest-server:
    image: codalab/bundleserver:local-dev
    command: server
    ports:
      - 2900:2900
    environment:
      - CODALAB_HOME=/home/codalab
      - CODALAB_USERNAME=codalab
      - CODALAB_PASSWORD=TESTPASSWORD
    volumes:
      - ./files/config/config.json:/home/codalab/config.json
    depends_on:
      - db-initializer

  bundle-manager:
    image: codalab/bundleserver:local-dev
    # sleep 30 seconds to give db-initializer time to initialize the db
    # TODO (bkgoksel): use something better than sleep (still works but logs error messages if sleep time isn't enough)
    entrypoint: bash -c "sleep 5 && /opt/codalab-cli/codalab/bin/cl bundle-manager"
    environment:
      - CODALAB_HOME=/home/codalab
      - CODALAB_USERNAME=codalab
      - CODALAB_PASSWORD=TESTPASSWORD
    volumes:
      - ./files/config/config.json:/home/codalab/config.json
    depends_on:
      - db-initializer

  web-server:
    image: codalab/webserver:local-dev
    entrypoint: ["./manage", "runserver", "0.0.0.0:2700"]
    environment:
      - DJANGO_CONFIGURATION=Prod
      - DJANGO_SECRET_KEY=SECRET_KEY
      - DJANGO_ALLOWED_HOSTS=localhost:127.0.0.1
    ports:
      - 2700:2700
    volumes:
      - ./files/config/uwsgi.ini:/usr/local/etc/uwsgi.ini
      - webserver-static:/opt/codalab-worksheets/codalab/apps/web/static

  nginx:
    image: nginx:1.12.0
    command: /data/bin/wait-for-it.sh rest-server:2900 -- nginx
    ports:
      - 80:80
    volumes:
      - ./files/config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./files/wait-for-it.sh:/data/bin/wait-for-it.sh
      - webserver-static:/www/data

  tests:
    image: codalab/bundleserver:local-dev
    entrypoint: /data/bin/wait-for-it.sh rest-server:2900 -- /data/bin/run-tests.sh
    depends_on:
      - rest-server
    environment:
      - CODALAB_HOME=/home/codalab
      - CODALAB_USERNAME=codalab
      - CODALAB_PASSWORD=TESTPASSWORD
    volumes:
      - ./files/run-tests.sh:/data/bin/run-tests.sh
      - ./files/config/config.json:/home/codalab/config.json
      - ./files/wait-for-it.sh:/data/bin/wait-for-it.sh

