version: '3'

services:
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=ROOTPWD
      - MYSQL_DATABASE=codalab_bundles
      - MYSQL_USER=codalab
      - MYSQL_PASSWORD=TESTPASSWORD
    volumes:
      - ./files/config/conf.d:/etc/mysql/conf.d

  rest-server:
    image: codalab/bundleserver:local-dev
    entrypoint: ['bash', '-c', '/opt/codalab-cli/venv/bin/pip install /opt/codalab-cli && /data/bin/wait-for-it.sh mysql:3306 -- /opt/codalab-cli/venv/bin/python /opt/codalab-cli/scripts/create-root-user.py TESTPASSWORD && echo "root account created" && /opt/codalab-cli/codalab/bin/cl server']
    ports:
      - 2900:2900
    environment:
      - CODALAB_HOME=/home/codalab
      - CODALAB_USERNAME=codalab
      - CODALAB_PASSWORD=TESTPASSWORD
    volumes:
      - ./files/config/config.json:/home/codalab/config.json
      - ./files/wait-for-it.sh:/data/bin/wait-for-it.sh
    depends_on:
      - mysql

  bundle-manager:
    image: codalab/bundleserver:local-dev
    entrypoint: ['bash', '-c', '/data/bin/wait-for-it.sh rest-server:2900 -- /opt/codalab-cli/codalab/bin/cl bundle-manager']
    environment:
      - CODALAB_HOME=/home/codalab
      - CODALAB_USERNAME=codalab
      - CODALAB_PASSWORD=TESTPASSWORD
    volumes:
      - ./files/config/config.json:/home/codalab/config.json
      - ./files/wait-for-it.sh:/data/bin/wait-for-it.sh
    depends_on:
      - rest-server

  worker:
    image: codalab/worker:local-dev
    entrypoint: ['bash', '-c', '/data/bin/wait-for-it.sh rest-server:2900 -- cl-worker --verbose']
    environment:
      - CODALAB_USERNAME=codalab
      - CODALAB_PASSWORD=TESTPASSWORD
    volumes:
      - ./files/wait-for-it.sh:/data/bin/wait-for-it.sh
    depends_on:
      - bundle-manager
