version: '3'

services:
  mysql:
    image: mysql:5.5.53
    environment:
      - MYSQL_ROOT_PASSWORD=ROOTPWD
    volumes:
      - ./files/config/conf.d:/etc/mysql/conf.d

  db-initializer:
    image: codalab/bundleserver:local-dev
    entrypoint: ['bash', '-c', '/data/bin/wait-for-it.sh mysql:3306 -- /data/bin/initialize-db.sh']
    depends_on:
      - mysql
    environment:
      - CODALAB_HOME=/home/codalab
      - CODALAB_USERNAME=codalab
      - CODALAB_PASSWORD=TESTPASSWORD
    volumes:
      - ./files/initialize-db.sh:/data/bin/initialize-db.sh
      - ./files/config/config.json:/home/codalab/config.json
      - ./files/wait-for-it.sh:/data/bin/wait-for-it.sh

  rest-server:
    image: codalab/bundleserver:local-dev
    entrypoint: ['bash', '-c', '/data/bin/wait-for-it.sh mysql:3306 -- /opt/codalab-cli/codalab/bin/cl server']
    ports:
      - 2900:2900
    environment:
      - CODALAB_HOME=/home/codalab
      - CODALAB_USERNAME=codalab
      - CODALAB_PASSWORD=TESTPASSWORD
    volumes:
      - ./files/config/config.json:/home/codalab/config.json
      - ./files/wait-for-it.sh:/data/bin/wait-for-it.sh
    depends_on:
      - db-initializer

  bundle-manager:
    image: codalab/bundleserver:local-dev
    # sleep 30 seconds to give db-initializer time to initialize the db
    # TODO (bkgoksel): use something better than sleep (still works but logs error messages if sleep time isn't enough)
    entrypoint: ['bash', '-c', '/data/bin/wait-for-it.sh rest-server:2900 -- /opt/codalab-cli/codalab/bin/cl bundle-manager']
    environment:
      - CODALAB_HOME=/home/codalab
      - CODALAB_USERNAME=codalab
      - CODALAB_PASSWORD=TESTPASSWORD
    volumes:
      - ./files/config/config.json:/home/codalab/config.json
      - ./files/wait-for-it.sh:/data/bin/wait-for-it.sh
    depends_on:
      - db-initializer
