version: '3'

volumes:
  codalab_home:

services:
  mysql:
    image: mysql:5.5.53
    environment:
      - MYSQL_ROOT_PASSWORD=ROOTPWD
      - MYSQL_DATABASE=codalab_bundles
      - MYSQL_USER=codalab
      - MYSQL_PASSWORD=TESTPASSWORD
    volumes:
      - ./files/config/conf.d:/etc/mysql/conf.d
    logging:
      driver: json-file
      options:
        mode: non-blocking

  rest-server:
    image: codalab/bundleserver:local-dev
    entrypoint: ['bash', '-c', '/opt/codalab-cli/venv/bin/pip install /opt/codalab-cli && /data/bin/wait-for-it.sh mysql:3306 -- /opt/codalab-cli/codalab/bin/cl config server/engine_url mysql://codalab:TESTPASSWORD@mysql:3306/codalab_bundles && /opt/codalab-cli/codalab/bin/cl config cli/default_address http://rest-server:2900 && /opt/codalab-cli/codalab/bin/cl config server/rest_host 0.0.0.0 && /opt/codalab-cli/codalab/bin/cl config server/secret_key SECRET_KEY && /opt/codalab-cli/venv/bin/python /opt/codalab-cli/scripts/create-root-user.py TESTPASSWORD && echo "root account created" && /opt/codalab-cli/codalab/bin/cl server']
    ports:
      - 2900:2900
    environment:
      - CODALAB_HOME=/home/codalab
      - CODALAB_USERNAME=codalab
      - CODALAB_PASSWORD=TESTPASSWORD
    volumes:
      - codalab_home:/home/codalab
      - ./files/wait-for-it.sh:/data/bin/wait-for-it.sh
    depends_on:
      - mysql
    logging:
      driver: json-file
      options:
        mode: non-blocking

  bundle-manager:
    image: codalab/bundleserver:local-dev
    entrypoint: ['bash', '-c', '/data/bin/wait-for-it.sh rest-server:2900 -- /opt/codalab-cli/codalab/bin/cl logout && /opt/codalab-cli/codalab/bin/cl new home && /opt/codalab-cli/codalab/bin/cl new dashboard && /opt/codalab-cli/codalab/bin/cl bundle-manager']
    environment:
      - CODALAB_HOME=/home/codalab
      - CODALAB_USERNAME=codalab
      - CODALAB_PASSWORD=TESTPASSWORD
    volumes:
      - codalab_home:/home/codalab
      - ./files/wait-for-it.sh:/data/bin/wait-for-it.sh
    depends_on:
      - rest-server
    logging:
      driver: json-file
      options:
        mode: non-blocking

  worker:
    image: codalab/worker:local-dev
    entrypoint: ['bash', '-c', '/data/bin/wait-for-it.sh rest-server:2900 -- cl-worker --server http://rest-server:2900 --verbose --work-dir /var/codalab/worker-dir']
    environment:
      - CODALAB_USERNAME=codalab
      - CODALAB_PASSWORD=TESTPASSWORD
    privileged: true
    volumes:
      - ./files/wait-for-it.sh:/data/bin/wait-for-it.sh
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/codalab/worker-dir/:/var/codalab/worker-dir/
    depends_on:
      - bundle-manager
    logging:
      driver: json-file
      options:
        mode: non-blocking
